project:
  type: website

website:
  title: "Biogeoinformatics (Babak Naimi)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - test.qmd
      - amphibians.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true



